version: '2.1'

services:
  building_knowledge_stack:
    # image: building_knowledge_stack
    build: .
    volumes:
      - .:/app
    command: ["./run_web.sh"]
    ports:
      - 7005:8000
    environment:
      DJANGO_RUN_ENV: TEST
    depends_on:
      - db

  db:
    image: postgres:11.3
    restart: always
    environment:
      POSTGRES_PASSWORD: password@123/
      POSTGRES_USER: building_user
      POSTGRES_DB: building_knowledge_stack_db

  redis:
    image: redis:5.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes